name: google_places_search_field
description: "A customizable Flutter widget for searching locations using Google Places Autocomplete with LatLng callback support"
version: 1.0.2
homepage: https://github.com/iampranavk/google-places-search-field
repository: https://github.com/iampranavk/google-places-search-field

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk: ^0.4.2+1
  google_maps_flutter: ^2.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

platforms:
  android:
  ios: